project:
  type: website
  output-dir: docs

website:
  title: "Haddi's Site"
  navbar:
    left:
      - href: index.qmd
        text: "About Website Creator"
      - text: "DataViz"
        menu: 
          - text: "Makeup Shades"
            href: shades.qmd
          - text: "PhDs Awarded in the US"
            href: phd.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

