---
title: "Ethics"
---

<h1>Target and Pregnancy Predictions</h1>

A 2012 article in the New York Times tells the story of how Target created a pregnancy predictor. Andrew Pole, a statistician began working at Target in 2002. Two colleagues in the marketing department asked him if he could predict if a customer was pregnant even if she did not want them to know. They went on this journey of creating an algorithm to predict pregnancy because of the fact that new parents are a holy grail for retailers. Most people remain consistent in their shopping habits and it is hard to change them as a retailer. The prime time to change people's shopping habits is when they go through a big change in life, becoming parents is one of those changes. Wanting to seize the opportunity to gain new customers or change the shopping habits of infrequent customers, Target developed this algorithm and used it to advertise ads for baby items to pregnant women. This algorithm was allegly so specific it could estimate the month that the baby is due based on a woman's change in shopping habits. This algorithm tracks 25 items that when analyzed together could give rise to a pregnancy score. An example of some of these items are unscented lotion, a large purse that could double as a diaper bag, and zinc and magnesium supplements.

<a href=https://www.nytimes.com/2012/02/19/magazine/shopping-habits.html?smid=url-share>Source</a>

An article by the Medium in 2020 dissects this article by the New York Times and addresses how the article might make the algorithm seem more advanced than it actually is. The original New York Times article, emphasizes a story where a father finds out that his teenage daughter was pregnant through the ads. The Medium article argues that the odds of Andrew Pole finding out that this happened in a random target is low and there is no proof that the target algorithm predicted that this specific girl was pregnant as opposed to her getting a random ad that happened to have some maternity things. The article then states that even if the story is true, it does not tell us about how good the algorithm itself is. The article uses the New York Times article as an example of how not to report an algorithm. This article advocates for the reporting of accuracy, false positive rate, false negative rate, precision, and recall of these algorithms so people can really gain a sense of how effective these algorithms are.

<a href=https://medium.com/\@colin.fraser/target-didnt-figure-out-a-teen-girl-was-pregnant-before-her-father-did-a6be13b973a5\>Source</a>

However, neither of these articles address the fact that there is no consent from customers to do this. Even in the original article with an interview with Andrew Pole, his colleagues in the marketing department state they would like to know that the customer is pregnant even if she does not want them to know she was pregnant. On their website, they probably have the little cookies warning that tells them that they are tracking their information or if they become a member of a rewards program the customers are not aware that they are using the shopping history in order to predict whether they are pregnant or not. This sort of algorithm exists outside of the ordinary person's imagination of what a company could do with their data.

One good thing about the data is that it was not publicly made available. Target has specific customer ids for each shopper and it is possible that if this data was publicly made available it could be used in other companies to predict pregnancy or it could reveal private information about a lot of people.

The people who were measured were customers at Target. These individuals were the intended audience of target for who the algorithm was intended for. There is no indication that they were informed that their data would be used for this specific algorithm. If this data was publicly made available it should not be analyzed because there is no indication that the customers were willing participants in the study to create this specific algorithm.

The observations for the algorithm are based on 25 items and how these were collected began with finding customers registered for a baby registry. Pole then found that women who were registered were buying unscented lotion early in their pregnancies. Then another analyst noticed that pregnant women were buying zinc and magnesium supplements sometime in the first 20 weeks. This practice of using the baby registry shows that participants in the study did not know or give their permission for their data to be used to create an invasive algorithm like this. Informed consent could have been possible by creating a survey for pregnant customers or customers that have previously been pregnant asking what products helped them while pregnant or what products they bought a lot of when pregnant. They could have compared the top results to the customer profiles of all the pregnant people who filled out the survey.
